sonar.projectKey=Gingerminds-Laravel-Multisite
sonar.qualitygate.wait=true
sonar.exclusions=resources/libs/**,resources/js/pages/**,resources/scss/custom/**,database/migrations/next/**,vendor/**,node_modules/**,storage/**,public/build/**,resources/lang/**/*.php
sonar.sources=.
